#暴露所有actuator接口
management:
  endpoints:
    web:
      exposure:
        include: '*'

#多数据源配置
spring:
  datasource:
    db1:
      url: jdbc:h2:mem:db1
      username: walter
      password: 123456
      driver-class-name: org.h2.Driver

    db2:
      url: jdbc:h2:mem:db2
      username: wyg
      password: 54321
      driver-class-name: org.h2.Driver

#  h2:
#    console:
#      enabled: true
#      path: /db1

  #h2配置

#  sql:
#    init:
#      schema-locations: classpath:db/schema.sql
#      data-locations: classpath:db/data.sql
#      platform: h2
#      mode: embedded



