#暴露所有actuator接口
management:
  endpoints:
    web:
      exposure:
        include: '*'

#多数据源配置
spring:
  datasource:
    url: jdbc:h2:mem:bean1
    username: walter
    password: 123456
    driver-class-name: org.h2.Driver



  #h2配置
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      platform: h2


